Lmm/contributing
cisagov/dotgov pull request #34
Opened 2022-08-10 15:49 UTC by loganmeetsworld

# Add documentation for contributing to this repo

## 🗣 Description ##

This adds documentation from previous conversations we've had about PR etiquette and other rules for contributing here, especially helpful for onboarding.

2022-08-10 16:05 UTC, SSPJ approved these changes
LGTM 👍

2022-08-10 16:08 UTC, h-m-f-t requested changes
👍 , flagged a small spelling error

2022-08-10 16:08 UTC, h-m-f-t commented on CONTRIBUTING.md
> +# Conributing
Conributing -> Contributing

2022-08-10 16:20 UTC, colinmurphy01 commented on CONTRIBUTING.md
> +- User research related scheduling or documentation
I would like to add user research synthesis to our repo at some point to demonstrate our understanding. This doesn't need to be a blocker, but something to consider later on.

2022-08-10 17:00 UTC, loganmeetsworld commented on CONTRIBUTING.md
> +# Conributing
Thanks! Fixed

2022-08-15 15:05 UTC, h-m-f-t approved these changes
🇺🇸

2022-08-15 15:06 UTC, merged